### ISSUE TITLE
Post: Fazendo o seu próprio power bank

### ISSUE THREAD

**Issue by Calebe94** [Calebe94/calebe94.github.io#1]
# TODO

- [] - Editar o nome do artigo (Talvez colocar algum nome mais atrativo)
- [] - Revisar a ortografia
- [] - Inserir alguma foto do primeiro power bank uma vez que não tenho mais as fotos da construção
- [] - Inserir o esquemático e a descrição dos componentes

# Ideias

* Considerar a separação em dois artigos, uma vez que foram feitos dois power banks(Parte I e  Parte II talvez).
